version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: example-app
    ports:
      - 5432:5432
    volumes:
      - data-volume:/var/lib/postgresql/data    
    networks:
      - web

networks:
    web:
      
volumes:
    data-volume: